// ============================================================
// AddServerModal — Manual server entry (host + port + token)
// ============================================================
// Modal for adding a local Stavi server connection, with an
// optional "Scan QR Code" shortcut (onPairQr) rendered INSIDE the
// modal — RN Modals are separate native windows, so anything a
// parent renders as a sibling is invisible underneath them.

import React, { useState, useCallback, useRef, useMemo } from 'react';
import {
  View,
  Text,
  TextInput,
  StyleSheet,
  Modal,
  Pressable,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { X, QrCode } from 'lucide-react-native';
import { useConnectionStore, type SavedConnection } from '../stores/connection';
import { classifyConnectError } from '../utils/connect-errors';
import { useTheme } from '../theme';
import { typography, spacing, radii } from '../theme';
// Dev-only module: loaded via conditional require so Metro's __DEV__ constant
// folding strips BOTH the branch and the module (with its real bearer token)
// from release bundles — a static import would bake the token into the APK.
type DevConnectionConfig = {
  name: string;
  androidHost: string;
  iosHost: string;
  port: number;
  bearerToken: string;
} | null;
let devConnectionConfig: DevConnectionConfig = null;
if (__DEV__) {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    devConnectionConfig = require('../generated/dev-config').devConnectionConfig;
  } catch {
    // dev-config.ts is gitignored and generated by postinstall; a fresh clone
    // that bundles before postinstall (or with --ignore-scripts) won't have it.
    // Fall back to no dev autofill rather than failing the bundle.
    devConnectionConfig = null;
  }
}
import { AnimatedPressable } from './AnimatedPressable';

// ----------------------------------------------------------
// Props
// ----------------------------------------------------------

interface AddServerModalProps {
  visible: boolean;
  onClose: () => void;
  onComplete: (connection: SavedConnection) => void;
  /** When provided, shows a "Scan QR Code" shortcut under the Connect button. */
  onPairQr?: () => void;
}

// Minimal base64url → utf8 decoder (Hermes has no Buffer; atob typing is
// unreliable across RN versions). Pairing codes are tiny, perf irrelevant.
const B64_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
function decodeBase64Url(input: string): string {
  const b64 = input.replace(/-/g, '+').replace(/_/g, '/');
  const bytes: number[] = [];
  let buffer = 0;
  let bits = 0;
  for (const ch of b64) {
    if (ch === '=') break;
    const val = B64_ALPHABET.indexOf(ch);
    if (val < 0) throw new Error('invalid base64');
    buffer = (buffer << 6) | val;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes.push((buffer >> bits) & 0xff);
    }
  }
  // UTF-8 decode (pairing JSON is ASCII in practice; handle 2/3-byte anyway)
  let out = '';
  for (let i = 0; i < bytes.length; ) {
    const b = bytes[i];
    if (b < 0x80) { out += String.fromCharCode(b); i += 1; }
    else if (b < 0xe0) { out += String.fromCharCode(((b & 0x1f) << 6) | (bytes[i + 1] & 0x3f)); i += 2; }
    else { out += String.fromCharCode(((b & 0x0f) << 12) | ((bytes[i + 1] & 0x3f) << 6) | (bytes[i + 2] & 0x3f)); i += 3; }
  }
  return out;
}

// ----------------------------------------------------------
// Component
// ----------------------------------------------------------

export function AddServerModal({ visible, onClose, onComplete, onPairQr }: AddServerModalProps) {
  const { colors } = useTheme();
  const devCfg = devConnectionConfig;
  const defaultHost = Platform.OS === 'android'
    ? (devCfg?.androidHost ?? '')
    : (devCfg?.iosHost ?? '');
  const [name, setName] = useState('');
  const [host, setHost] = useState(defaultHost);
  const [port, setPort] = useState(String(devCfg?.port ?? 3773));
  const [token, setToken] = useState(devCfg?.bearerToken ?? '');
  const [error, setError] = useState<string | null>(null);
  const [connecting, setConnecting] = useState(false);
  // Captured from a pasted RELAY pairing code — without this, pasting the
  // CLI's relay string silently created a broken LAN-direct entry.
  const [relayFields, setRelayFields] = useState<{
    relayUrl: string; serverPublicKey: string; roomId: string;
  } | null>(null);

  const hostRef = useRef<TextInput>(null);
  const portRef = useRef<TextInput>(null);
  const tokenRef = useRef<TextInput>(null);

  const addServer = useConnectionStore((s) => s.addServer);

  const resetForm = useCallback(() => {
    setName('');
    setHost(defaultHost);
    setPort(String(devCfg?.port ?? 3773));
    setToken(devCfg?.bearerToken ?? '');
    setRelayFields(null);
    setError(null);
  }, [defaultHost, devCfg]);

  const handleClose = useCallback(() => {
    resetForm();
    onClose();
  }, [resetForm, onClose]);

  // Smart host input: a pasted pairing code (base64url JSON from the CLI
  // banner) fills EVERYTHING; "host:port" and full http URLs split correctly
  // — previously a pasted "192.168.1.5:3773" silently built a broken URL.
  // Splitting only triggers on paste-sized input jumps: char-by-char typing
  // of "host:3..." must NOT split mid-keystroke.
  const lastHostLenRef = useRef(0);
  const handleSmartHostInput = useCallback((text: string) => {
    const trimmed = text.trim();
    const isPaste = text.length - lastHostLenRef.current > 3;
    lastHostLenRef.current = text.length;
    if (!isPaste) {
      setHost(text);
      setRelayFields(null); // manual edit — pasted relay pairing no longer applies
      return;
    }

    // Pairing code? (base64url blob that decodes to a payload with a token)
    if (/^[A-Za-z0-9_-]{40,}$/.test(trimmed)) {
      try {
        const decoded = JSON.parse(decodeBase64Url(trimmed)) as {
          token?: string; lanHost?: string; port?: number; name?: string;
          relay?: string; roomId?: string; serverPublicKey?: string;
        };
        if (decoded.token && (decoded.lanHost || decoded.port)) {
          if (decoded.lanHost) setHost(decoded.lanHost);
          if (decoded.port) setPort(String(decoded.port));
          setToken(decoded.token);
          setRelayFields(
            decoded.relay && decoded.roomId && decoded.serverPublicKey
              ? { relayUrl: decoded.relay, serverPublicKey: decoded.serverPublicKey, roomId: decoded.roomId }
              : null,
          );
          return;
        }
      } catch { /* not a pairing code — fall through to plain text */ }
    }

    // http(s)://host:port[/...] or host:port
    const urlMatch = /^(?:https?:\/\/)?([^\s/:]+)(?::(\d{1,5}))?(?:\/.*)?$/.exec(trimmed);
    if (urlMatch && urlMatch[2]) {
      setHost(urlMatch[1]);
      setPort(urlMatch[2]);
      return;
    }

    setHost(text);
  }, []);

  const handleConnect = useCallback(async () => {
    const trimmedHost = host.trim();
    const trimmedToken = token.trim();
    const portNum = parseInt(port, 10);

    if (!trimmedHost) {
      setError('Host is required');
      hostRef.current?.focus();
      return;
    }

    if (isNaN(portNum) || portNum < 1 || portNum > 65535) {
      setError('Port must be between 1 and 65535');
      portRef.current?.focus();
      return;
    }

    if (!trimmedToken) {
      setError('Bearer token is required');
      tokenRef.current?.focus();
      return;
    }

    setError(null);
    setConnecting(true);

    try {
      const connection = await addServer({
        // Leave blank when the user didn't type one — addServer defaults it to
        // the server's reported hostname (then host:port). User can edit later.
        name: name.trim(),
        host: trimmedHost,
        port: portNum,
        bearerToken: trimmedToken,
        ...(relayFields ?? {}),
      });

      resetForm();
      onComplete(connection);
    } catch (err) {
      // addServer now throws when the LAN server is unreachable, so the server
      // is NOT saved on failure — show the user exactly why.
      const friendly = classifyConnectError(err, { host: trimmedHost, port: portNum });
      setError(`${friendly.title}. ${friendly.message}`);
    } finally {
      setConnecting(false);
    }
  }, [addServer, name, host, onComplete, port, resetForm, token, relayFields]);

  const styles = useMemo(() => StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg.base,
    },
    keyboardView: {
      flex: 1,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[3],
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.divider,
    },
    headerTitle: {
      fontSize: typography.fontSize.lg,
      fontWeight: typography.fontWeight.semibold,
      color: colors.fg.primary,
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: radii.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    form: {
      flex: 1,
    },
    formContent: {
      paddingHorizontal: spacing[4],
      paddingTop: spacing[6],
      paddingBottom: spacing[8],
    },
    field: {
      marginBottom: spacing[5],
    },
    fieldLabel: {
      fontSize: typography.fontSize.sm,
      fontWeight: typography.fontWeight.medium,
      color: colors.fg.secondary,
      marginBottom: spacing[2],
    },
    input: {
      backgroundColor: colors.bg.input,
      borderRadius: radii.md,
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[3],
      fontSize: typography.fontSize.base,
      fontFamily: typography.fontFamily.mono,
      color: colors.fg.primary,
    },
    tokenInput: {
      minHeight: 80,
      paddingTop: spacing[3],
    },
    fieldHint: {
      fontSize: typography.fontSize.xs,
      color: colors.fg.muted,
      marginTop: spacing[1],
      marginLeft: spacing[1],
    },
    code: {
      fontFamily: typography.fontFamily.mono,
      color: colors.accent.primary,
    },
    errorBox: {
      backgroundColor: colors.semantic.errorSubtle,
      borderRadius: radii.md,
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[3],
      marginBottom: spacing[5],
    },
    errorText: {
      fontSize: typography.fontSize.sm,
      color: colors.semantic.error,
    },
    connectButton: {
      backgroundColor: colors.accent.primary,
      borderRadius: radii.md,
      paddingVertical: spacing[4],
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
    },
    qrRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing[2],
      paddingVertical: spacing[4],
    },
    qrRowText: {
      fontSize: typography.fontSize.base,
      color: colors.accent.primary,
      fontWeight: typography.fontWeight.medium,
    },
    connectButtonPressed: {
      backgroundColor: colors.accent.secondary,
    },
    connectButtonText: {
      fontSize: typography.fontSize.base,
      fontWeight: typography.fontWeight.semibold,
      color: colors.fg.onAccent,
    },
  }), [colors]);

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={handleClose}
    >
      <SafeAreaView style={styles.container}>
        <KeyboardAvoidingView
          style={styles.keyboardView}
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        >
          {/* Header */}
          <View style={styles.header}>
            <Text style={styles.headerTitle}>Add Server</Text>
            <Pressable
              style={styles.closeButton}
              onPress={handleClose}
              hitSlop={12}
            >
              <X size={20} color={colors.fg.secondary} />
            </Pressable>
          </View>

          <ScrollView
            style={styles.form}
            contentContainerStyle={styles.formContent}
            keyboardShouldPersistTaps="handled"
          >
            {/* Name (optional) */}
            <View style={styles.field}>
              <Text style={styles.fieldLabel}>Name (optional)</Text>
              <TextInput
                style={styles.input}
                value={name}
                onChangeText={setName}
                placeholder="My Dev Machine"
                placeholderTextColor={colors.fg.muted}
                returnKeyType="next"
                onSubmitEditing={() => hostRef.current?.focus()}
                autoCapitalize="words"
              />
            </View>

            {/* Host — accepts plain host, host:port, http URLs, and full
                pairing codes (everything `stavi serve` prints) */}
            <View style={styles.field}>
              <Text style={styles.fieldLabel}>Host</Text>
              <TextInput
                ref={hostRef}
                style={styles.input}
                value={host}
                onChangeText={(text) => {
                  handleSmartHostInput(text);
                  setError(null);
                }}
                placeholder="192.168.1.5 — or paste the pairing code"
                placeholderTextColor={colors.fg.muted}
                autoCapitalize="none"
                autoCorrect={false}
                keyboardType="url"
                returnKeyType="next"
                onSubmitEditing={() => portRef.current?.focus()}
              />
            </View>

            {/* Port */}
            <View style={styles.field}>
              <Text style={styles.fieldLabel}>Port</Text>
              <TextInput
                ref={portRef}
                style={styles.input}
                value={port}
                onChangeText={(text) => {
                  setPort(text);
                  setError(null);
                }}
                placeholder="3773"
                placeholderTextColor={colors.fg.muted}
                keyboardType="number-pad"
                returnKeyType="next"
                onSubmitEditing={() => tokenRef.current?.focus()}
              />
            </View>

            {/* Bearer Token */}
            <View style={styles.field}>
              <Text style={styles.fieldLabel}>Bearer Token</Text>
              <TextInput
                ref={tokenRef}
                style={[styles.input, styles.tokenInput]}
                value={token}
                onChangeText={(text) => {
                  setToken(text);
                  setError(null);
                }}
                placeholder="sk-stavi-…"
                placeholderTextColor={colors.fg.muted}
                autoCapitalize="none"
                autoCorrect={false}
                multiline
                numberOfLines={3}
                textAlignVertical="top"
                returnKeyType="done"
              />
              <Text style={styles.fieldHint}>
                Copy the token printed by <Text style={styles.code}>stavi serve</Text> on your computer
              </Text>
            </View>

            {/* Error */}
            {error && (
              <View style={styles.errorBox}>
                <Text style={styles.errorText}>{error}</Text>
              </View>
            )}

            {/* Connect Button */}
            <AnimatedPressable
              style={[styles.connectButton, connecting && styles.connectButtonPressed]}
              onPress={() => void handleConnect()}
              disabled={connecting}
              haptic="medium"
            >
              <Text style={styles.connectButtonText}>{connecting ? 'Connecting…' : 'Connect'}</Text>
            </AnimatedPressable>

            {/* QR pairing shortcut — `stavi serve` prints a QR in both modes */}
            {onPairQr ? (
              <Pressable style={styles.qrRow} onPress={onPairQr} hitSlop={6}>
                <QrCode size={18} color={colors.accent.primary} />
                <Text style={styles.qrRowText}>Scan QR code instead</Text>
              </Pressable>
            ) : null}
          </ScrollView>
        </KeyboardAvoidingView>
      </SafeAreaView>
    </Modal>
  );
}
